name: Docker Image CI

on: workflow_dispatch

env:

  REGISTRY: https://gcr.io
  IMAGE_NAME: ${{ secret.GCP_PROJECT_ID }}/node-contact-api
  IMAGE_TAG: ${{ github.run_number }}


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      ref: container-based

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: _json_key
        password: ${{ secret.SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        registry: ${{ env.REGISTRY }}
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        file: Dockerfile.min
