name: Docker Image CI

on: workflow_dispatch

env:

  REGISTRY: gcr.io
  IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/node-contact-api
  IMAGE_TAG: ${{ github.run_number }}


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: container-based

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Run NPM install
      run: npm install

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        registry: ${{ env.REGISTRY }}
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        file: Dockerfile.min
