name: Docker Image CI

on: workflow_dispatch

jobs:

  build-container:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/node-contact-api
      IMAGE_TAG: ${{ github.run_number }}
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: container-based

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Configure node
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Build Docker image
      run: |-
        npm install --prefix ./node_modules
        docker build Dockerfile.min -t $IMAGE_NAME:latest

    - name: Push Docker Image to Google Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$IMAGE_NAME:$IMAGE_TAG
        docker push gcr.io/$IMAGE_NAME:$IMAGE_TAG
